import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <section className={styles.container_principal}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container_texto}>
        <h1>Olá Mundo! Estamos começando React</h1>
        <p>Parágrafo com React.js</p>
        <p className={styles.autor}>Criado por Leandro Lopes</p>
      </div>
    </section> // Elemento pai
  );
}
