import Head from "next/head";
import Image from "next/image";
import Logo from "../../public/next.svg";
import estilos from "@/styles/Home.module.css";
import Card from "@/componentes/Card";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Image className={estilos.img_logo} src={Logo} alt="logotipo"/>
      </div>

      <div>
        <Link className={estilos.link} href="https://www.youtube.com/">
          Youtube
        </Link>
      </div>

      <main className={estilos.main_container}>
        <Card/>
        <Card/>
        <Card/>
      </main>
      
    </div>
  );
}
