import Head from "next/head";
import estilos from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo";
import Rodape from "@/componentes/Rodape";
import Secao_capa from "@/componentes/Secao_capa";
import Secao_produtos from "@/componentes/Secao_produtos";
import Secao_sobre from "@/componentes/Secao_sobre";
import Secao_contatos from "@/componentes/Secao_contatos";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topo/>

      <main className={estilos.container_main}>
        <Secao_capa/>
        <Secao_produtos/>
        <Secao_sobre/>
        <Secao_contatos/>
      </main>
      
      <Rodape/>
      
    </div>
  );
}
