CREATE TABLE IF NOT EXISTS medicos (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL,
    descricao VARCHAR(100) NOT NULL
);